/* StutterSuite local P0 prototype — no network requests, no automatic recording. */
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const STORE = 'stuttersuite.public.v1';
const SCHEMA_VERSION = 4;
const defaultProfiles = [
  {id:'meeting', name:'会議用', scene:'通話・会議', condition:{mode:'daf',branches:[{enabled:true,delay:50,pitch:0,gain:0,pan:'both'},{enabled:false,delay:200,pitch:0,gain:-6,pan:'both'}],masterGain:-24,masking:{enabled:false,type:'white',gain:-42,filter:'none'},direct:{enabled:false,gain:-18,pan:'both'},metronome:{enabled:false,bpm:60,type:'visual'},choral:{continuous:false,countdown:0,rate:1.2,pause:0}}},
  {id:'presentation', name:'発表前', scene:'発表', condition:{mode:'none',branches:[{enabled:false,delay:50,pitch:0,gain:0,pan:'both'},{enabled:false,delay:200,pitch:0,gain:-6,pan:'both'}],masterGain:-27,masking:{enabled:false,type:'white',gain:-42,filter:'none'},direct:{enabled:false,gain:-18,pan:'both'},metronome:{enabled:false,bpm:60,type:'visual'},choral:{continuous:true,countdown:1,rate:1.2,pause:.5}}}
];
let data = JSON.parse(localStorage.getItem(STORE) || 'null') || {schema_version:SCHEMA_VERSION, profiles:JSON.parse(JSON.stringify(defaultProfiles)), script:'', phrases:[], reflections:[]};
function defaultCondition(){return JSON.parse(JSON.stringify(defaultProfiles[0].condition));}
function numberInRange(value,fallback,min,max){const number=Number(value);return Number.isFinite(number)?Math.max(min,Math.min(max,number)):fallback;}
function normalizeCondition(value={}){
  const mode=['daf','none','custom'].includes(value.mode)?value.mode:'custom';
  const branches=Array.isArray(value.branches)?value.branches:[];
  const condition={
    mode,
    branches:[0,1].map(i=>{
      const branch=branches[i]||{};
      return {enabled:typeof branch.enabled==='boolean'?branch.enabled:i===0,delay:numberInRange(branch.delay,i?200:50,0,300),pitch:0,gain:numberInRange(branch.gain,i?-6:0,-60,0),pan:['left','right','both'].includes(branch.pan)?branch.pan:'both'};
    }),
    masterGain:numberInRange(value.masterGain??value.master,-24,-60,0),
    masking:{enabled:!!value.masking?.enabled,type:['white','pink','brown'].includes(value.masking?.type)?value.masking.type:'white',gain:numberInRange(value.masking?.gain,-42,-60,-12),filter:['none','lowpass','highpass'].includes(value.masking?.filter)?value.masking.filter:'none'},
    direct:{enabled:!!value.direct?.enabled,gain:numberInRange(value.direct?.gain,-18,-60,0),pan:['left','right','both'].includes(value.direct?.pan)?value.direct.pan:'both'},
    metronome:{enabled:!!value.metronome?.enabled,bpm:numberInRange(value.metronome?.bpm,60,30,180),type:['visual','sound','both'].includes(value.metronome?.type)?value.metronome.type:'visual'},
    choral:{continuous:!!value.choral?.continuous,countdown:numberInRange(value.choral?.countdown,0,0,5),rate:numberInRange(value.choral?.rate,1.2,.5,2),pause:numberInRange(value.choral?.pause,0,0,5)}
  };
  return condition;
}
function withoutAssistance(value){const condition=normalizeCondition(value);condition.branches.forEach(branch=>branch.enabled=false);condition.masking.enabled=false;condition.direct.enabled=false;condition.metronome.enabled=false;return condition;}
function migrateData(){
  if(!Array.isArray(data.profiles)||!data.profiles.length)data.profiles=JSON.parse(JSON.stringify(defaultProfiles));
  data.profiles=data.profiles.map(profile=>{
    if(profile.condition)return {...profile,condition:profile.condition.mode==='none'?withoutAssistance(profile.condition):normalizeCondition(profile.condition)};
    const legacyMode=profile.mode||'daf';
    if(['faf','combo'].includes(legacyMode)){
      const condition=withoutAssistance({mode:'custom',branches:[{enabled:false,delay:profile.delayA??50,gain:0,pan:'both'},{enabled:false,delay:200,gain:-6,pan:'both'}],masterGain:profile.master??-24});
      return {id:profile.id||crypto.randomUUID(),name:profile.name||'保存した設定',scene:profile.scene||'通話・会議',condition,migrationNote:'旧FAF／DAF+FAF設定はWeb版で再現できないため、音声フィードバックを無効化しました。'};
    }
    return {id:profile.id||crypto.randomUUID(),name:profile.name||'保存した設定',scene:profile.scene||'通話・会議',condition:legacyMode==='none'?withoutAssistance({mode:'none'}):normalizeCondition({mode:'daf',branches:[{enabled:true,delay:profile.delayA??50,gain:0,pan:'both'},{enabled:!!profile.branchB,delay:200,gain:-6,pan:'both'}],masterGain:profile.master??-24})};
  });
  data.reflections=Array.isArray(data.reflections)?data.reflections:[];
  data.reflections.forEach(reflection=>{if(!reflection.conditionSnapshot)reflection.conditionSnapshot=null;});
  data.schema_version=SCHEMA_VERSION;
}
migrateData();
data.ttsRate=typeof data.ttsRate==='number'&&Number.isFinite(data.ttsRate)?Math.min(2,Math.max(.5,data.ttsRate)):1.2;
let audio = new AssistanceAudioEngine({onPulse:()=>{const pulse=$('#pulse');pulse.classList.add('active');setTimeout(()=>pulse.classList.remove('active'),90);}});
let activeProfile = data.profiles[0]?.id || 'meeting';
let activeConditionName = data.profiles[0]?.name || '未選択';
let sessionConditionSnapshot = null;
let phraseIndex = 0, speaking = false, trialStep = 0, toastTimer;
let speechToken = 0, advanceTimer = null;

function publicData(){const {schema_version,profiles,script,phrases,reflections,ttsRate}=data;return {schema_version:SCHEMA_VERSION,profiles,script,phrases,reflections,ttsRate};}
function persist(){ localStorage.setItem(STORE, JSON.stringify(publicData())); }
function toast(message){ const node=$('#toast'); node.textContent=message; node.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>node.classList.remove('show'),3500); }
function now(){ return new Date().toLocaleString('ja-JP',{dateStyle:'medium',timeStyle:'short'}); }
function setStatus(kind, state, text){ const n=$(`#${kind}Status`); n.className=`status ${state}`; n.innerHTML=`<i></i>${text}`; }
function go(page){ $$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page)); $$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${page}`)); window.scrollTo({top:0,behavior:'smooth'}); }
function profileSummary(profile){const c=profile.condition;if(profile.migrationNote)return 'FAF未対応（無効化）';const parts=[];if(c.branches.some(x=>x.enabled))parts.push('DAF');if(c.masking.enabled)parts.push('マスキング');if(c.direct.enabled)parts.push('直接フィードバック');if(c.metronome.enabled)parts.push('メトロノーム');if(c.choral.continuous)parts.push('斉読/TTS');return parts.join(' + ')||(c.mode==='none'?'補助なし':'カスタム');}
function renderProfiles(){ const select=$('#profileSelect'); const cards=$('#profileCards'); select.innerHTML=''; cards.innerHTML=''; data.profiles.forEach(p=>{ const o=document.createElement('option'); o.value=p.id;o.textContent=`${p.name}（${p.scene}）`;select.append(o); const card=document.createElement('article');card.className='profile-card';card.innerHTML=`<strong>${escapeHtml(p.name)}</strong><p>${escapeHtml(p.scene)} · ${escapeHtml(profileSummary(p))}</p><button class="secondary" data-use-profile="${p.id}">使う</button>`;cards.append(card); }); select.value=activeProfile; renderTrialSelectors(); }
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function selectedProfile(){return data.profiles.find(p=>p.id===activeProfile);}
async function stopAssistForConditionChange(){if(!audio.running)return false;await clearAudio();setStatus('assist','stopped','補助: 停止');setStatus('mic','idle','マイク: 未使用');$('#startAssist').disabled=false;$('#muteAssist').disabled=true;return true;}
async function loadCondition(name,condition){const wasRunning=await stopAssistForConditionChange();activeConditionName=name;sessionConditionSnapshot=null;applyCondition(condition);return wasRunning;}
async function applyProfile(id){const p=data.profiles.find(x=>x.id===id);if(!p)return;activeProfile=id;$('#profileSelect').value=id;const wasRunning=await loadCondition(p.name,p.condition);const note=p.migrationNote?` ${p.migrationNote}`:'';toast(`${wasRunning?`補助を停止して「${p.name}」を読み込みました。必要なら改めて開始してください。`:`「${p.name}」を選びました。音声はまだ開始していません。`}${note}`);}
function selectMode(mode){$$('.mode').forEach(x=>x.classList.toggle('selected',x.dataset.mode===mode));}
function markCustomForExtraModules(){if($('.mode.selected')?.dataset.mode==='daf'&&(!$('#branchAEnabled').checked||$('#branchBEnabled').checked||$('#maskingEnabled').checked||$('#directEnabled').checked||$('#metroEnabled').checked))selectMode('custom');}
function currentCondition(){return normalizeCondition({mode:$('.mode.selected')?.dataset.mode||'custom',branches:[{enabled:$('#branchAEnabled').checked,delay:$('#delayA').value,gain:$('#gainA').value,pan:$('#panA').value},{enabled:$('#branchBEnabled').checked,delay:$('#delayB').value,gain:$('#gainB').value,pan:$('#panB').value}],masterGain:$('#masterGain').value,masking:{enabled:$('#maskingEnabled').checked,type:$('#maskingType').value,gain:$('#maskingGain').value,filter:$('#maskingFilter').value},direct:{enabled:$('#directEnabled').checked,gain:$('#directGain').value,pan:$('#directPan').value},metronome:{enabled:$('#metroEnabled').checked,bpm:$('#bpm').value,type:$('#metroType').value},choral:{continuous:$('#continuousChoral').checked,countdown:$('#choralCountdown').value,rate:$('#ttsRate').value,pause:$('#phrasePause').value}});}
function applyCondition(condition){const c=normalizeCondition(condition);selectMode(c.mode);[['A',c.branches[0]],['B',c.branches[1]]].forEach(([name,b])=>{$(`#branch${name}Enabled`).checked=b.enabled;$(`#delay${name}`).value=b.delay;$(`#gain${name}`).value=b.gain;$(`#pan${name}`).value=b.pan;});$('#masterGain').value=c.masterGain;$('#maskingEnabled').checked=c.masking.enabled;$('#maskingType').value=c.masking.type;$('#maskingGain').value=c.masking.gain;$('#maskingFilter').value=c.masking.filter;$('#directEnabled').checked=c.direct.enabled;$('#directGain').value=c.direct.gain;$('#directPan').value=c.direct.pan;$('#metroEnabled').checked=c.metronome.enabled;$('#bpm').value=c.metronome.bpm;$('#metroType').value=c.metronome.type;$('#continuousChoral').checked=c.choral.continuous;$('#choralCountdown').value=c.choral.countdown;$('#phrasePause').value=c.choral.pause;setTtsRate(c.choral.rate,false);syncControls();refreshAudio();}
function syncControls(){ ['delayA','delayB','gainA','gainB','bpm','masterGain','ttsRate','phrasePause','maskingGain','directGain','choralCountdown'].forEach(id=>{const unit=id.startsWith('delay')?' ms':id.startsWith('gain')||id==='masterGain'?' dB':id==='bpm'?' BPM':id==='ttsRate'?' 倍':id==='choralCountdown'||id==='phrasePause'?' 秒':'';const label=id==='phrasePause'?'pause':id;const out=$(`#${label}Value`);if(out)out.textContent=`${Number($(`#${id}`).value).toFixed(id==='ttsRate'?2:id==='phrasePause'?1:0)}${unit}`;});$('#latencyReadout').textContent=`${$('#delayA').value} ms`;}
function setTtsRate(value,save=true){const input=value==null?NaN:Number(value),rate=Math.round(Math.min(2,Math.max(.5,Number.isFinite(input)?input:1.2))*20)/20;data.ttsRate=rate;['ttsRate','compactRate'].forEach(id=>$(`#${id}`).value=String(rate));['ttsRateValue','compactRateValue'].forEach(id=>$(`#${id}`).textContent=`${rate.toFixed(2)} 倍`);if(save)persist();}
function gain(value){return Math.pow(10,Number(value)/20);}

async function enumerateDevices(){
  try { const devices=await navigator.mediaDevices.enumerateDevices(); const input=$('#inputDevice'); const current=input.value; input.innerHTML='<option value="default">既定のマイク（ブラウザが選択）</option>'; devices.filter(d=>d.kind==='audioinput').forEach((d,i)=>input.add(new Option(d.label||`マイク ${i+1}`,d.deviceId))); input.value=[...input.options].some(x=>x.value===current)?current:'default';
    const output=$('#outputDevice'),currentOutput=output.value;output.innerHTML='<option value="default">ブラウザの既定の出力</option>';devices.filter(d=>d.kind==='audiooutput').forEach((d,i)=>output.add(new Option(d.label||`出力 ${i+1}`,d.deviceId)));output.value=[...output.options].some(x=>x.value===currentOutput)?currentOutput:'default';
  } catch { toast('機器一覧を取得できませんでした。ブラウザの権限を確認してください。'); }
}
async function prepareAudio(){
  if(!navigator.mediaDevices?.getUserMedia){$('#audioMessage').textContent='このブラウザはマイク入力に対応していません。';return false;}
  try{ const device=$('#inputDevice').value; const constraints={audio:device==='default'?true:{deviceId:{exact:device}},video:false}; const stream=await navigator.mediaDevices.getUserMedia(constraints); stream.getTracks().forEach(t=>t.stop()); await enumerateDevices(); $('#audioMessage').textContent='マイクを確認しました。補助はまだ停止中です。'; toast('マイクを確認しました。'); return true;
  }catch(e){ $('#audioMessage').textContent='マイクを使えません。ブラウザの権限・他アプリの利用状況を確認してください。';return false; }
}
async function clearAudio(){await audio.stop();}
async function startAssist(){
  if(audio.running)return;if(!navigator.mediaDevices?.getUserMedia){toast('このブラウザではライブ補助を利用できません。');return;}
  try{
    const condition=currentCondition();const result=await audio.start({inputDeviceId:$('#inputDevice').value,outputDeviceId:$('#outputDevice').value,settings:condition});sessionConditionSnapshot=JSON.parse(JSON.stringify(condition));setStatus('assist','running','補助: 動作中');setStatus('mic','running','マイク: 使用中');$('#startAssist').disabled=true;$('#muteAssist').disabled=false;$('#audioMessage').textContent=result.warnings[0]||'補助音をヘッドホンへ再生しています。相手へのミュートではありません。TTSの出力先はOS/ブラウザの設定に従います。';
  }catch(e){try{await audio.stop();}catch{}sessionConditionSnapshot=null;setStatus('assist','stopped','補助: 停止');setStatus('mic','idle','マイク: 未使用');$('#startAssist').disabled=false;$('#muteAssist').disabled=true;$('#audioMessage').textContent='補助を開始できませんでした。マイク権限、ヘッドホン、他アプリの設定を確認してください。';}
}
function refreshAudio(){if(audio.running&&!audio.muted)audio.configure(currentCondition());}
function muteAssist(){if(!audio.running)return;audio.mute();setStatus('assist','muted','補助: 停止');$('#muteAssist').disabled=true;$('#audioMessage').textContent='補助音を停止しました。通話のマイクは通話アプリ側で操作します。';}
async function emergencyStop(){pausePhrase();await clearAudio();setStatus('assist','stopped','補助: 停止');setStatus('mic','idle','マイク: 未使用');setStatus('record','idle','録音: OFF');$('#startAssist').disabled=false;$('#muteAssist').disabled=true;$('#audioMessage').textContent='補助音・マスキング・メトロノーム・TTSを停止し、マイクを解放しました。';toast('補助音を停止しました。');}

function splitPhrases(text){return text.replace(/\r/g,'').split(/(?<=[。！？!?…]|\n)/).map(x=>x.trim()).filter(Boolean).map((text,i)=>({id:`p${Date.now()}-${i}`,text,reading:text}));}
function renderPhrases(){const list=$('#phraseList');list.innerHTML='';phraseIndex=Math.min(phraseIndex,Math.max(0,data.phrases.length-1));if(!data.phrases.length){list.innerHTML='<p class="empty">原稿を句に分けると、ここに表示されます。</p>';updatePlayer();return;}data.phrases.forEach((p,i)=>{const b=document.createElement('button');b.className=`phrase ${i===phraseIndex?'active':''}`;b.textContent=`${i+1}. ${p.reading}`;b.onclick=()=>{pausePhrase();phraseIndex=i;renderPhrases();};list.append(b);});updatePlayer();}
function updatePlayer(){const p=data.phrases[phraseIndex],n=data.phrases[phraseIndex+1];$('#currentPhrase').textContent=p?.reading||'—';$('#nextPhrase').textContent=n?.reading||'—';}
function loadVoices(){const voices=speechSynthesis.getVoices(),jp=voices.filter(v=>v.lang.toLowerCase().startsWith('ja')),all=jp.length?jp:voices,sel=$('#voiceSelect'),prev=sel.value;sel.innerHTML='';all.forEach(v=>sel.add(new Option(`${v.name} (${v.lang})`,v.name)));if(!all.length)sel.add(new Option('利用可能な音声がありません',''));if([...sel.options].some(x=>x.value===prev))sel.value=prev;}
function playPhrase({skipCountdown=false}={}){const p=data.phrases[phraseIndex];if(!p){toast('まず原稿を句に分けてください。');return;}pausePhrase();const token=speechToken,index=phraseIndex,start=()=>{if(token!==speechToken)return;const u=new SpeechSynthesisUtterance(p.reading),voice=speechSynthesis.getVoices().find(v=>v.name===$('#voiceSelect').value);if(voice)u.voice=voice;u.lang=voice?.lang||'ja-JP';u.rate=Number($('#ttsRate').value);speaking=true;u.onend=()=>{if(token!==speechToken)return;speaking=false;if($('#continuousChoral').checked&&index<data.phrases.length-1){advanceTimer=setTimeout(()=>{advanceTimer=null;if(token!==speechToken)return;phraseIndex=index+1;renderPhrases();playPhrase({skipCountdown:true});},Number($('#phrasePause').value)*1000);}};u.onerror=()=>{if(token===speechToken)speaking=false;};speechSynthesis.speak(u);};const countdown=!skipCountdown?Number($('#choralCountdown').value)*1000:0;if(countdown){toast(`${countdown/1000} 秒後に読み上げます。`);advanceTimer=setTimeout(()=>{advanceTimer=null;start();},countdown);}else start();}
function pausePhrase(){speechToken++;if(advanceTimer!==null){clearTimeout(advanceTimer);advanceTimer=null;}speechSynthesis.cancel();speaking=false;}
function nextPhrase(){pausePhrase();phraseIndex=Math.min(phraseIndex+1,Math.max(0,data.phrases.length-1));renderPhrases();}
function previousPhrase(){pausePhrase();renderPhrases();}
function renderHistory(){const box=$('#historyList');box.innerHTML='';if(!data.reflections.length){box.innerHTML='<p class="empty">まだ履歴はありません。</p>';return;}data.reflections.slice().reverse().forEach(r=>{const x=document.createElement('div');x.className='history-item';const condition=r.conditionSnapshot?` · 条件: ${escapeHtml(conditionLabel(r.conditionSnapshot))}`:' · 条件スナップショットなし（旧履歴）';x.innerHTML=`<strong>${escapeHtml(r.profile)}</strong><br><small>${escapeHtml(r.at)}${condition} · 負担: ${r.effort??'未回答'} · 自然さ: ${r.naturalness??'未回答'} · 次も使う: ${r.wouldUse||'未回答'}</small>${r.note?`<div>${escapeHtml(r.note)}</div>`:''}`;box.append(x);});}
function conditionLabel(condition){const c=normalizeCondition(condition),labels=[];if(c.branches.some(b=>b.enabled))labels.push('DAF');if(c.masking.enabled)labels.push('マスキング');if(c.direct.enabled)labels.push('直接');if(c.metronome.enabled)labels.push('メトロノーム');if(c.choral.continuous)labels.push('斉読/TTS');return labels.join(' + ')||'補助なし';}
function download(filename,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}

$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('.goto').forEach(b=>b.onclick=()=>go(b.dataset.target));
function saveCurrentProfile(){const name=prompt('現在の設定の名前を入力してください',selectedProfile()?.name||'新しい設定');if(!name?.trim())return;const existing=selectedProfile();if(existing&&confirm(`「${existing.name}」を現在の設定で更新しますか？\n「キャンセル」を選ぶと新しい設定として保存します。`)){existing.name=name.trim();existing.condition=currentCondition();delete existing.migrationNote;activeConditionName=existing.name;}else{const profile={id:crypto.randomUUID(),name:name.trim(),scene:'通話・会議',condition:currentCondition()};data.profiles.push(profile);activeProfile=profile.id;activeConditionName=profile.name;}persist();renderProfiles();toast('現在の補助条件を保存しました。');}
$('#newProfile').onclick=async()=>{const name=prompt('設定の名前を入力してください','新しい設定');if(!name?.trim())return;const p={id:crypto.randomUUID(),name:name.trim(),scene:'通話・会議',condition:currentCondition()};data.profiles.push(p);persist();renderProfiles();await applyProfile(p.id);go('assist');};
$('#saveCurrentProfile').onclick=saveCurrentProfile;
$('#profileCards').onclick=async e=>{const id=e.target.dataset.useProfile;if(id){await applyProfile(id);go('assist');}};$('#profileSelect').onchange=async e=>applyProfile(e.target.value);
$$('.mode').forEach(b=>b.onclick=()=>{const mode=b.dataset.mode;selectMode(mode);if(mode==='none'){$('#branchAEnabled').checked=false;$('#branchBEnabled').checked=false;$('#directEnabled').checked=false;$('#maskingEnabled').checked=false;$('#metroEnabled').checked=false;}else if(mode==='daf'){$('#branchAEnabled').checked=true;$('#branchBEnabled').checked=false;$('#directEnabled').checked=false;$('#maskingEnabled').checked=false;$('#metroEnabled').checked=false;}refreshAudio();});
['delayA','delayB','gainA','gainB','bpm','masterGain','ttsRate','phrasePause','maskingGain','directGain','choralCountdown'].forEach(id=>{$(`#${id}`).oninput=()=>{if(id==='ttsRate'){setTtsRate($('#ttsRate').value);return;}syncControls();markCustomForExtraModules();if(id==='masterGain')audio.setMasterGain($('#masterGain').value);else refreshAudio();};});
['branchAEnabled','branchBEnabled','panA','panB','maskingEnabled','maskingType','maskingFilter','directEnabled','directPan','metroEnabled','metroType','continuousChoral'].forEach(id=>{$(`#${id}`).onchange=e=>{if(['branchAEnabled','branchBEnabled','maskingEnabled','directEnabled','metroEnabled'].includes(id)&&e.target.checked&&$('.mode.selected')?.dataset.mode==='none')selectMode('custom');markCustomForExtraModules();refreshAudio();};});
$('#prepareAudio').onclick=prepareAudio;$('#startAssist').onclick=startAssist;$('#muteAssist').onclick=muteAssist;$('#emergency').onclick=emergencyStop;$('#applyPreset').onclick=()=>{selectMode('custom');$('#branchAEnabled').checked=true;$('#delayA').value=50;$('#branchBEnabled').checked=true;$('#delayB').value=200;$('#gainB').value=-6;syncControls();refreshAudio();toast('2系統のDAF候補を設定しました。FAFはこのWeb版では未対応です。');};
$('#scriptText').value=data.script||'';$('#charCount').textContent=`${$('#scriptText').value.length.toLocaleString()} / 50,000 文字`;$('#scriptText').oninput=()=>$('#charCount').textContent=`${$('#scriptText').value.length.toLocaleString()} / 50,000 文字`;
$('#splitScript').onclick=()=>{pausePhrase();data.script=$('#scriptText').value;data.phrases=splitPhrases(data.script);phraseIndex=0;persist();renderPhrases();toast(`${data.phrases.length} 句に分けました。`);};$('#saveScript').onclick=()=>{data.script=$('#scriptText').value;persist();toast('原稿をこの端末に保存しました。');};$('#txtImport').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#scriptText').value=r.result;$('#scriptText').dispatchEvent(new Event('input'));toast('TXTを読み込みました。');};r.readAsText(f,'utf-8');};
$('#playPhrase').onclick=playPhrase;$('#repeatPhrase').onclick=playPhrase;$('#pausePhrase').onclick=pausePhrase;$('#nextPhraseBtn').onclick=nextPhrase;$('#previousPhrase').onclick=previousPhrase;
['effort','naturalness'].forEach(id=>{$(`#${id}`).oninput=()=>{$(`#${id}Out`).textContent=$(`#${id}`).value;};});$('#saveReflection').onclick=()=>{const conditionSnapshot=sessionConditionSnapshot||currentCondition();data.reflections.push({id:crypto.randomUUID(),at:now(),profile:activeConditionName,conditionSnapshot:JSON.parse(JSON.stringify(conditionSnapshot)),effort:$('#effort').value,naturalness:$('#naturalness').value,wouldUse:$('#wouldUse').value,note:$('#sessionNote').value});persist();renderHistory();toast('開始時の補助条件のコピーと振り返りを保存しました。');};
$('#exportData').onclick=()=>download(`stuttersuite-export-${new Date().toISOString().slice(0,10)}.json`,publicData());$('#backupData').onclick=()=>download(`stuttersuite-backup-${new Date().toISOString().slice(0,10)}.json`,publicData());$('#restoreData').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const restored=JSON.parse(r.result);if(!restored||!Array.isArray(restored.profiles)||!Array.isArray(restored.phrases))throw new Error();await emergencyStop();sessionConditionSnapshot=null;data=restored;migrateData();setTtsRate(data.ttsRate,false);phraseIndex=0;persist();renderProfiles();await applyProfile(data.profiles[0].id);$('#scriptText').value=data.script||'';$('#scriptText').dispatchEvent(new Event('input'));renderPhrases();renderHistory();toast('バックアップを復元・移行しました。補助は停止したままです。');}catch{toast('復元できませんでした。StutterSuite のバックアップを選んでください。');}};r.readAsText(f);};$('#clearData').onclick=()=>{if(confirm('このブラウザに保存した設定・原稿・履歴を削除します。元に戻せません。')){localStorage.removeItem(STORE);location.reload();}};
$('#refreshDevices').onclick=enumerateDevices;$('#outputDevice').onchange=async e=>{if(audio.running&&typeof audio.context?.setSinkId==='function'){try{await audio.context.setSinkId(e.target.value==='default'?'':e.target.value);toast('補助音の出力先を変更しました。');}catch{toast('この出力先へ変更できませんでした。OSまたはブラウザの既定出力を確認してください。');}}else if(e.target.value!=='default')toast('開始時にこの出力先を適用します。TTSの出力先は切り替えられません。');};
let trial={order:[],index:0,active:false};
function renderTrialSelectors(){const options=[{id:'baseline',name:'補助なし'},...data.profiles.map(p=>({id:p.id,name:p.name}))];['trialProfileA','trialProfileB'].forEach((id,index)=>{const select=$(`#${id}`);if(!select)return;const value=select.value||options[Math.min(index,options.length-1)].id;select.innerHTML='';options.forEach(option=>select.add(new Option(option.name,option.id)));select.value=options.some(option=>option.id===value)?value:options[0].id;});}
function openTrial(){renderTrialSelectors();$('#trialModal').classList.add('open');$('#trialModal').setAttribute('aria-hidden','false');const configuring=!trial.active;['trialProfileA','trialProfileB','trialRandomize'].forEach(id=>$(`#${id}`).disabled=!configuring);$('#trialStartButton').textContent=configuring?'比較を開始':'この条件を準備';$('#trialNext').hidden=configuring;if(configuring){$('#trialStep').textContent='準備';$('#trialCondition').textContent='条件を選んで「比較を開始」を押してください。';}else updateTrial();}
async function applyTrialCondition(){const id=trial.order[trial.index];if(id==='baseline')await loadCondition('補助なし',withoutAssistance({...defaultCondition(),mode:'none'}));else await applyProfile(id);sessionConditionSnapshot=JSON.parse(JSON.stringify(currentCondition()));go('assist');$('#trialModal').classList.remove('open');$('#trialModal').setAttribute('aria-hidden','true');toast(`比較 ${trial.index+1}/${trial.order.length} の条件を準備しました。補助はまだ開始していません。`);}
$('#startTrial').onclick=openTrial;$$('[data-close-modal]').forEach(b=>b.onclick=()=>{$('#trialModal').classList.remove('open');$('#trialModal').setAttribute('aria-hidden','true');});function updateTrial(){const id=trial.order[trial.index],profile=data.profiles.find(p=>p.id===id);$('#trialStep').textContent=`${trial.index+1} / ${trial.order.length}`;$('#trialCondition').textContent=id==='baseline'?'補助なし':profile?.name||'保存済みの設定';$('#trialNext').textContent=trial.index<trial.order.length-1?'次の条件へ':'比較を終える';}$('#trialStartButton').onclick=async()=>{if(!trial.active){trial.order=[$('#trialProfileA').value,$('#trialProfileB').value];if($('#trialRandomize').checked&&Math.random()<.5)trial.order.reverse();trial.index=0;trial.active=true;}await applyTrialCondition();};$('#trialNext').onclick=()=>{if(trial.index<trial.order.length-1){trial.index++;updateTrial();}else{trial={order:[],index:0,active:false};$('#trialModal').classList.remove('open');$('#trialModal').setAttribute('aria-hidden','true');toast('比較を終えました。必要なら振り返りを残せます。');go('history');}};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){emergencyStop();return;}if(e.ctrlKey&&e.altKey){if(e.code==='F12'){e.preventDefault();emergencyStop();}if(e.code==='F9'){e.preventDefault();speaking?pausePhrase():playPhrase();}if(e.code==='F10'){e.preventDefault();nextPhrase();}if(e.code==='F8'){e.preventDefault();previousPhrase();}}});
window.addEventListener('beforeunload',emergencyStop);speechSynthesis.onvoiceschanged=loadVoices;renderProfiles();applyCondition(selectedProfile()?.condition||defaultCondition());renderPhrases();renderHistory();loadVoices();enumerateDevices();
